* 1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):<br>zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],<br>ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].<br>Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная).<br>Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [3]:
b = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp ** 2) - np.mean(zp) ** 2)
b

2.620538882402765

In [4]:
a = np.mean(ks) - b * np.mean(zp)
a

444.1773573243596

In [5]:
X = zp
X = X.reshape(10, 1)
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [6]:
y = ks
y = y.reshape(10, 1)
y

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [7]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([[5.88982042]])

* 2) Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [8]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [9]:
def mse_(B1, y=y, X=X, n=10):
    """Mean squared error."""
    
    return np.sum((B1 * X - y) ** 2) / n

In [10]:
alpha = 1e-6

In [11]:
B1 = 0.1
n = 10

In [12]:
for i in range(300):
    B1 -= alpha * (2 / n) * np.sum((B1 * X - y) * X)
    if i % 10 == 0:
        print(f'Iteration {i}, B1={B1}, mse={mse_(B1)}')

Iteration 0, B1=0.25952808, mse=493237.7212546963
Iteration 10, B1=1.6319792141937546, mse=306275.7568040035
Iteration 20, B1=2.6698789606516935, mse=199352.96411174876
Iteration 30, B1=3.4547782236263824, mse=138204.25062502263
Iteration 40, B1=4.04834889855975, mse=103233.54824312925
Iteration 50, B1=4.497229618367758, mse=83233.94472982832
Iteration 60, B1=4.836690291080364, mse=71796.25222021657
Iteration 70, B1=5.093403362579137, mse=65255.0820486468
Iteration 80, B1=5.287539550879594, mse=61514.21323463749
Iteration 90, B1=5.434352720103083, mse=59374.825462025976
Iteration 100, B1=5.54537842245223, mse=58151.31823171113
Iteration 110, B1=5.629340281237233, mse=57451.59938606899
Iteration 120, B1=5.692835432193034, mse=57051.433003054815
Iteration 130, B1=5.740852880272922, mse=56822.57946410561
Iteration 140, B1=5.777165500770666, mse=56691.69904907657
Iteration 150, B1=5.804626485478126, mse=56616.849068093856
Iteration 160, B1=5.825393526544474, mse=56574.04266614384
Iteration

* 3) Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [13]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [14]:
def mse_(B1, B0, y=y, X=X, n=10):
    """Mean squared error."""
    
    return np.sum((B1 * X + B0 - y) ** 2) / n

In [15]:
B1 = 0.1
B0 = 0.1

In [16]:
for i in range(20000000):
    y_pred = B0 + B1 * X
    B0 -= alpha * (2 / n) * np.sum(y_pred - y)
    B1 -= alpha * (2 / n) * np.sum((y_pred - y) * X)
    if i % 500000 == 0:
        print(f'Iteration {i}, B0={B0}, B1={B1}, mse={mse_(B1, B0)}')

Iteration 0, B0=0.10139932, B1=0.2595078, mse=493102.2473380378
Iteration 500000, B0=99.62326925415903, B1=5.156609306712451, mse=36584.8831651681
Iteration 1000000, B0=176.81634536031407, B1=4.588434137551724, mse=24602.866672921762
Iteration 1500000, B0=236.71526880642702, B1=4.147551578153019, mse=17388.28338336958
Iteration 2000000, B0=283.1945803067062, B1=3.8054432958269095, mse=13044.25564183225
Iteration 2500000, B0=319.2607777147802, B1=3.5399801371216335, mse=10428.639983674579
Iteration 3000000, B0=347.2467902759279, B1=3.33399071134467, mse=8853.731700793858
Iteration 3500000, B0=368.96288333142047, B1=3.1741506652199787, mse=7905.451668998496
Iteration 4000000, B0=385.8137546931221, B1=3.0501208017996615, mse=7334.47555027671
Iteration 4500000, B0=398.88939702545025, B1=2.9538782931601695, mse=6990.680766858188
Iteration 5000000, B0=409.03560363595057, B1=2.8791977266112596, mse=6783.6758690522665
Iteration 5500000, B0=416.9086783168232, B1=2.821248416073767, mse=6659.0345